name: On Push Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Client build and verify
      run: |
        cd client
        yarn install
        yarn verify
        cd ..
        yarn install
        yarn verify
        yarn packclient
      env:
        CI: true
